language: php

php:
  - 5.3
  - 5.4

before_install:
  - cd ~/builds
  - git clone git://github.com/laravel/laravel.git
  - mv ./Anahkiasen/cerberus-laravel ./laravel/bundles/cerberus
  - echo "<?php return array('connections' => array('mysql' => array('driver' => 'mysql', 'host' => 'localhost', 'database' => 'laravel_taketime', 'username' => 'root', 'password' => 'root', 'charset' => 'utf8', 'prefix' => '', ), ),);" > application/config/local/database.php
  - echo "<?php return array('cerberus' => array('auto' => true));" > ./laravel/application/bundles.php
  - cd ./laravel

script: "php artisan test cerberus --env=local"